name: Update files

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: README.md # List of files to update
          prefix: "jib-container-publish.yml@" # Prefix before the version, default is: ""

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # You need to create your own token with pull request rights
          commit-message: update tags in readme
          title: Update tags in readme
          body: Update readme to reflect release changes
          branch: update-readme
          base: main
